/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SwaggerRouteImport } from './routes/swagger'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWishlistRouteImport } from './routes/api/wishlist'
import { Route as ApiTransactionsRouteImport } from './routes/api/transactions'
import { Route as ApiSavingsRouteImport } from './routes/api/savings'
import { Route as ApiPaymentAccountsRouteImport } from './routes/api/payment-accounts'
import { Route as ApiGoalsRouteImport } from './routes/api/goals'
import { Route as ApiExchangeRateRouteImport } from './routes/api/exchange-rate'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiWishlistIdRouteImport } from './routes/api/wishlist/$id'
import { Route as ApiTransactionsIdRouteImport } from './routes/api/transactions/$id'
import { Route as ApiSettingsCurrencyRouteImport } from './routes/api/settings/currency'
import { Route as ApiSettingsAiRouteImport } from './routes/api/settings/ai'
import { Route as ApiSavingsIdRouteImport } from './routes/api/savings/$id'
import { Route as ApiPaymentAccountsIdRouteImport } from './routes/api/payment-accounts/$id'
import { Route as ApiOpenapiJsonRouteImport } from './routes/api/openapi.json'
import { Route as ApiGoalsIdRouteImport } from './routes/api/goals/$id'
import { Route as ApiCategoriesIdRouteImport } from './routes/api/categories/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiTransactionRouteImport } from './routes/api/ai/transaction'
import { Route as ApiAiConversationsRouteImport } from './routes/api/ai/conversations'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as ApiSettingsAiRevealRouteImport } from './routes/api/settings/ai/reveal'
import { Route as ApiAiConversationsConversationIdRouteImport } from './routes/api/ai/conversations/$conversationId'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SwaggerRoute = SwaggerRouteImport.update({
  id: '/swagger',
  path: '/swagger',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWishlistRoute = ApiWishlistRouteImport.update({
  id: '/api/wishlist',
  path: '/api/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsRoute = ApiTransactionsRouteImport.update({
  id: '/api/transactions',
  path: '/api/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSavingsRoute = ApiSavingsRouteImport.update({
  id: '/api/savings',
  path: '/api/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentAccountsRoute = ApiPaymentAccountsRouteImport.update({
  id: '/api/payment-accounts',
  path: '/api/payment-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoalsRoute = ApiGoalsRouteImport.update({
  id: '/api/goals',
  path: '/api/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExchangeRateRoute = ApiExchangeRateRouteImport.update({
  id: '/api/exchange-rate',
  path: '/api/exchange-rate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWishlistIdRoute = ApiWishlistIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiWishlistRoute,
} as any)
const ApiTransactionsIdRoute = ApiTransactionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTransactionsRoute,
} as any)
const ApiSettingsCurrencyRoute = ApiSettingsCurrencyRouteImport.update({
  id: '/api/settings/currency',
  path: '/api/settings/currency',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsAiRoute = ApiSettingsAiRouteImport.update({
  id: '/api/settings/ai',
  path: '/api/settings/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSavingsIdRoute = ApiSavingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSavingsRoute,
} as any)
const ApiPaymentAccountsIdRoute = ApiPaymentAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPaymentAccountsRoute,
} as any)
const ApiOpenapiJsonRoute = ApiOpenapiJsonRouteImport.update({
  id: '/api/openapi/json',
  path: '/api/openapi/json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoalsIdRoute = ApiGoalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiGoalsRoute,
} as any)
const ApiCategoriesIdRoute = ApiCategoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCategoriesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTransactionRoute = ApiAiTransactionRouteImport.update({
  id: '/api/ai/transaction',
  path: '/api/ai/transaction',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiConversationsRoute = ApiAiConversationsRouteImport.update({
  id: '/api/ai/conversations',
  path: '/api/ai/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsAiRevealRoute = ApiSettingsAiRevealRouteImport.update({
  id: '/reveal',
  path: '/reveal',
  getParentRoute: () => ApiSettingsAiRoute,
} as any)
const ApiAiConversationsConversationIdRoute =
  ApiAiConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => ApiAiConversationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/analytics': typeof AnalyticsRoute
  '/categories': typeof CategoriesRoute
  '/goals': typeof GoalsRoute
  '/privacy': typeof PrivacyRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/swagger': typeof SwaggerRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/wishlist': typeof WishlistRoute
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/exchange-rate': typeof ApiExchangeRateRoute
  '/api/goals': typeof ApiGoalsRouteWithChildren
  '/api/payment-accounts': typeof ApiPaymentAccountsRouteWithChildren
  '/api/savings': typeof ApiSavingsRouteWithChildren
  '/api/transactions': typeof ApiTransactionsRouteWithChildren
  '/api/wishlist': typeof ApiWishlistRouteWithChildren
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/conversations': typeof ApiAiConversationsRouteWithChildren
  '/api/ai/transaction': typeof ApiAiTransactionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/goals/$id': typeof ApiGoalsIdRoute
  '/api/openapi/json': typeof ApiOpenapiJsonRoute
  '/api/payment-accounts/$id': typeof ApiPaymentAccountsIdRoute
  '/api/savings/$id': typeof ApiSavingsIdRoute
  '/api/settings/ai': typeof ApiSettingsAiRouteWithChildren
  '/api/settings/currency': typeof ApiSettingsCurrencyRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/api/wishlist/$id': typeof ApiWishlistIdRoute
  '/api/ai/conversations/$conversationId': typeof ApiAiConversationsConversationIdRoute
  '/api/settings/ai/reveal': typeof ApiSettingsAiRevealRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/analytics': typeof AnalyticsRoute
  '/categories': typeof CategoriesRoute
  '/goals': typeof GoalsRoute
  '/privacy': typeof PrivacyRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/swagger': typeof SwaggerRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/wishlist': typeof WishlistRoute
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/exchange-rate': typeof ApiExchangeRateRoute
  '/api/goals': typeof ApiGoalsRouteWithChildren
  '/api/payment-accounts': typeof ApiPaymentAccountsRouteWithChildren
  '/api/savings': typeof ApiSavingsRouteWithChildren
  '/api/transactions': typeof ApiTransactionsRouteWithChildren
  '/api/wishlist': typeof ApiWishlistRouteWithChildren
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/conversations': typeof ApiAiConversationsRouteWithChildren
  '/api/ai/transaction': typeof ApiAiTransactionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/goals/$id': typeof ApiGoalsIdRoute
  '/api/openapi/json': typeof ApiOpenapiJsonRoute
  '/api/payment-accounts/$id': typeof ApiPaymentAccountsIdRoute
  '/api/savings/$id': typeof ApiSavingsIdRoute
  '/api/settings/ai': typeof ApiSettingsAiRouteWithChildren
  '/api/settings/currency': typeof ApiSettingsCurrencyRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/api/wishlist/$id': typeof ApiWishlistIdRoute
  '/api/ai/conversations/$conversationId': typeof ApiAiConversationsConversationIdRoute
  '/api/settings/ai/reveal': typeof ApiSettingsAiRevealRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/analytics': typeof AnalyticsRoute
  '/categories': typeof CategoriesRoute
  '/goals': typeof GoalsRoute
  '/privacy': typeof PrivacyRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/swagger': typeof SwaggerRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/wishlist': typeof WishlistRoute
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/exchange-rate': typeof ApiExchangeRateRoute
  '/api/goals': typeof ApiGoalsRouteWithChildren
  '/api/payment-accounts': typeof ApiPaymentAccountsRouteWithChildren
  '/api/savings': typeof ApiSavingsRouteWithChildren
  '/api/transactions': typeof ApiTransactionsRouteWithChildren
  '/api/wishlist': typeof ApiWishlistRouteWithChildren
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/conversations': typeof ApiAiConversationsRouteWithChildren
  '/api/ai/transaction': typeof ApiAiTransactionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/goals/$id': typeof ApiGoalsIdRoute
  '/api/openapi/json': typeof ApiOpenapiJsonRoute
  '/api/payment-accounts/$id': typeof ApiPaymentAccountsIdRoute
  '/api/savings/$id': typeof ApiSavingsIdRoute
  '/api/settings/ai': typeof ApiSettingsAiRouteWithChildren
  '/api/settings/currency': typeof ApiSettingsCurrencyRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/api/wishlist/$id': typeof ApiWishlistIdRoute
  '/api/ai/conversations/$conversationId': typeof ApiAiConversationsConversationIdRoute
  '/api/settings/ai/reveal': typeof ApiSettingsAiRevealRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/analytics'
    | '/categories'
    | '/goals'
    | '/privacy'
    | '/savings'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/swagger'
    | '/terms'
    | '/transactions'
    | '/wishlist'
    | '/api/categories'
    | '/api/exchange-rate'
    | '/api/goals'
    | '/api/payment-accounts'
    | '/api/savings'
    | '/api/transactions'
    | '/api/wishlist'
    | '/api/ai/chat'
    | '/api/ai/conversations'
    | '/api/ai/transaction'
    | '/api/auth/$'
    | '/api/categories/$id'
    | '/api/goals/$id'
    | '/api/openapi/json'
    | '/api/payment-accounts/$id'
    | '/api/savings/$id'
    | '/api/settings/ai'
    | '/api/settings/currency'
    | '/api/transactions/$id'
    | '/api/wishlist/$id'
    | '/api/ai/conversations/$conversationId'
    | '/api/settings/ai/reveal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/analytics'
    | '/categories'
    | '/goals'
    | '/privacy'
    | '/savings'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/swagger'
    | '/terms'
    | '/transactions'
    | '/wishlist'
    | '/api/categories'
    | '/api/exchange-rate'
    | '/api/goals'
    | '/api/payment-accounts'
    | '/api/savings'
    | '/api/transactions'
    | '/api/wishlist'
    | '/api/ai/chat'
    | '/api/ai/conversations'
    | '/api/ai/transaction'
    | '/api/auth/$'
    | '/api/categories/$id'
    | '/api/goals/$id'
    | '/api/openapi/json'
    | '/api/payment-accounts/$id'
    | '/api/savings/$id'
    | '/api/settings/ai'
    | '/api/settings/currency'
    | '/api/transactions/$id'
    | '/api/wishlist/$id'
    | '/api/ai/conversations/$conversationId'
    | '/api/settings/ai/reveal'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/analytics'
    | '/categories'
    | '/goals'
    | '/privacy'
    | '/savings'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/swagger'
    | '/terms'
    | '/transactions'
    | '/wishlist'
    | '/api/categories'
    | '/api/exchange-rate'
    | '/api/goals'
    | '/api/payment-accounts'
    | '/api/savings'
    | '/api/transactions'
    | '/api/wishlist'
    | '/api/ai/chat'
    | '/api/ai/conversations'
    | '/api/ai/transaction'
    | '/api/auth/$'
    | '/api/categories/$id'
    | '/api/goals/$id'
    | '/api/openapi/json'
    | '/api/payment-accounts/$id'
    | '/api/savings/$id'
    | '/api/settings/ai'
    | '/api/settings/currency'
    | '/api/transactions/$id'
    | '/api/wishlist/$id'
    | '/api/ai/conversations/$conversationId'
    | '/api/settings/ai/reveal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CategoriesRoute: typeof CategoriesRoute
  GoalsRoute: typeof GoalsRoute
  PrivacyRoute: typeof PrivacyRoute
  SavingsRoute: typeof SavingsRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SwaggerRoute: typeof SwaggerRoute
  TermsRoute: typeof TermsRoute
  TransactionsRoute: typeof TransactionsRoute
  WishlistRoute: typeof WishlistRoute
  ApiCategoriesRoute: typeof ApiCategoriesRouteWithChildren
  ApiExchangeRateRoute: typeof ApiExchangeRateRoute
  ApiGoalsRoute: typeof ApiGoalsRouteWithChildren
  ApiPaymentAccountsRoute: typeof ApiPaymentAccountsRouteWithChildren
  ApiSavingsRoute: typeof ApiSavingsRouteWithChildren
  ApiTransactionsRoute: typeof ApiTransactionsRouteWithChildren
  ApiWishlistRoute: typeof ApiWishlistRouteWithChildren
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiConversationsRoute: typeof ApiAiConversationsRouteWithChildren
  ApiAiTransactionRoute: typeof ApiAiTransactionRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOpenapiJsonRoute: typeof ApiOpenapiJsonRoute
  ApiSettingsAiRoute: typeof ApiSettingsAiRouteWithChildren
  ApiSettingsCurrencyRoute: typeof ApiSettingsCurrencyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swagger': {
      id: '/swagger'
      path: '/swagger'
      fullPath: '/swagger'
      preLoaderRoute: typeof SwaggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wishlist': {
      id: '/api/wishlist'
      path: '/api/wishlist'
      fullPath: '/api/wishlist'
      preLoaderRoute: typeof ApiWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions': {
      id: '/api/transactions'
      path: '/api/transactions'
      fullPath: '/api/transactions'
      preLoaderRoute: typeof ApiTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/savings': {
      id: '/api/savings'
      path: '/api/savings'
      fullPath: '/api/savings'
      preLoaderRoute: typeof ApiSavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment-accounts': {
      id: '/api/payment-accounts'
      path: '/api/payment-accounts'
      fullPath: '/api/payment-accounts'
      preLoaderRoute: typeof ApiPaymentAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/goals': {
      id: '/api/goals'
      path: '/api/goals'
      fullPath: '/api/goals'
      preLoaderRoute: typeof ApiGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exchange-rate': {
      id: '/api/exchange-rate'
      path: '/api/exchange-rate'
      fullPath: '/api/exchange-rate'
      preLoaderRoute: typeof ApiExchangeRateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wishlist/$id': {
      id: '/api/wishlist/$id'
      path: '/$id'
      fullPath: '/api/wishlist/$id'
      preLoaderRoute: typeof ApiWishlistIdRouteImport
      parentRoute: typeof ApiWishlistRoute
    }
    '/api/transactions/$id': {
      id: '/api/transactions/$id'
      path: '/$id'
      fullPath: '/api/transactions/$id'
      preLoaderRoute: typeof ApiTransactionsIdRouteImport
      parentRoute: typeof ApiTransactionsRoute
    }
    '/api/settings/currency': {
      id: '/api/settings/currency'
      path: '/api/settings/currency'
      fullPath: '/api/settings/currency'
      preLoaderRoute: typeof ApiSettingsCurrencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/ai': {
      id: '/api/settings/ai'
      path: '/api/settings/ai'
      fullPath: '/api/settings/ai'
      preLoaderRoute: typeof ApiSettingsAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/savings/$id': {
      id: '/api/savings/$id'
      path: '/$id'
      fullPath: '/api/savings/$id'
      preLoaderRoute: typeof ApiSavingsIdRouteImport
      parentRoute: typeof ApiSavingsRoute
    }
    '/api/payment-accounts/$id': {
      id: '/api/payment-accounts/$id'
      path: '/$id'
      fullPath: '/api/payment-accounts/$id'
      preLoaderRoute: typeof ApiPaymentAccountsIdRouteImport
      parentRoute: typeof ApiPaymentAccountsRoute
    }
    '/api/openapi/json': {
      id: '/api/openapi/json'
      path: '/api/openapi/json'
      fullPath: '/api/openapi/json'
      preLoaderRoute: typeof ApiOpenapiJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/goals/$id': {
      id: '/api/goals/$id'
      path: '/$id'
      fullPath: '/api/goals/$id'
      preLoaderRoute: typeof ApiGoalsIdRouteImport
      parentRoute: typeof ApiGoalsRoute
    }
    '/api/categories/$id': {
      id: '/api/categories/$id'
      path: '/$id'
      fullPath: '/api/categories/$id'
      preLoaderRoute: typeof ApiCategoriesIdRouteImport
      parentRoute: typeof ApiCategoriesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/transaction': {
      id: '/api/ai/transaction'
      path: '/api/ai/transaction'
      fullPath: '/api/ai/transaction'
      preLoaderRoute: typeof ApiAiTransactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/conversations': {
      id: '/api/ai/conversations'
      path: '/api/ai/conversations'
      fullPath: '/api/ai/conversations'
      preLoaderRoute: typeof ApiAiConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/ai/reveal': {
      id: '/api/settings/ai/reveal'
      path: '/reveal'
      fullPath: '/api/settings/ai/reveal'
      preLoaderRoute: typeof ApiSettingsAiRevealRouteImport
      parentRoute: typeof ApiSettingsAiRoute
    }
    '/api/ai/conversations/$conversationId': {
      id: '/api/ai/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/api/ai/conversations/$conversationId'
      preLoaderRoute: typeof ApiAiConversationsConversationIdRouteImport
      parentRoute: typeof ApiAiConversationsRoute
    }
  }
}

interface ApiCategoriesRouteChildren {
  ApiCategoriesIdRoute: typeof ApiCategoriesIdRoute
}

const ApiCategoriesRouteChildren: ApiCategoriesRouteChildren = {
  ApiCategoriesIdRoute: ApiCategoriesIdRoute,
}

const ApiCategoriesRouteWithChildren = ApiCategoriesRoute._addFileChildren(
  ApiCategoriesRouteChildren,
)

interface ApiGoalsRouteChildren {
  ApiGoalsIdRoute: typeof ApiGoalsIdRoute
}

const ApiGoalsRouteChildren: ApiGoalsRouteChildren = {
  ApiGoalsIdRoute: ApiGoalsIdRoute,
}

const ApiGoalsRouteWithChildren = ApiGoalsRoute._addFileChildren(
  ApiGoalsRouteChildren,
)

interface ApiPaymentAccountsRouteChildren {
  ApiPaymentAccountsIdRoute: typeof ApiPaymentAccountsIdRoute
}

const ApiPaymentAccountsRouteChildren: ApiPaymentAccountsRouteChildren = {
  ApiPaymentAccountsIdRoute: ApiPaymentAccountsIdRoute,
}

const ApiPaymentAccountsRouteWithChildren =
  ApiPaymentAccountsRoute._addFileChildren(ApiPaymentAccountsRouteChildren)

interface ApiSavingsRouteChildren {
  ApiSavingsIdRoute: typeof ApiSavingsIdRoute
}

const ApiSavingsRouteChildren: ApiSavingsRouteChildren = {
  ApiSavingsIdRoute: ApiSavingsIdRoute,
}

const ApiSavingsRouteWithChildren = ApiSavingsRoute._addFileChildren(
  ApiSavingsRouteChildren,
)

interface ApiTransactionsRouteChildren {
  ApiTransactionsIdRoute: typeof ApiTransactionsIdRoute
}

const ApiTransactionsRouteChildren: ApiTransactionsRouteChildren = {
  ApiTransactionsIdRoute: ApiTransactionsIdRoute,
}

const ApiTransactionsRouteWithChildren = ApiTransactionsRoute._addFileChildren(
  ApiTransactionsRouteChildren,
)

interface ApiWishlistRouteChildren {
  ApiWishlistIdRoute: typeof ApiWishlistIdRoute
}

const ApiWishlistRouteChildren: ApiWishlistRouteChildren = {
  ApiWishlistIdRoute: ApiWishlistIdRoute,
}

const ApiWishlistRouteWithChildren = ApiWishlistRoute._addFileChildren(
  ApiWishlistRouteChildren,
)

interface ApiAiConversationsRouteChildren {
  ApiAiConversationsConversationIdRoute: typeof ApiAiConversationsConversationIdRoute
}

const ApiAiConversationsRouteChildren: ApiAiConversationsRouteChildren = {
  ApiAiConversationsConversationIdRoute: ApiAiConversationsConversationIdRoute,
}

const ApiAiConversationsRouteWithChildren =
  ApiAiConversationsRoute._addFileChildren(ApiAiConversationsRouteChildren)

interface ApiSettingsAiRouteChildren {
  ApiSettingsAiRevealRoute: typeof ApiSettingsAiRevealRoute
}

const ApiSettingsAiRouteChildren: ApiSettingsAiRouteChildren = {
  ApiSettingsAiRevealRoute: ApiSettingsAiRevealRoute,
}

const ApiSettingsAiRouteWithChildren = ApiSettingsAiRoute._addFileChildren(
  ApiSettingsAiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AnalyticsRoute: AnalyticsRoute,
  CategoriesRoute: CategoriesRoute,
  GoalsRoute: GoalsRoute,
  PrivacyRoute: PrivacyRoute,
  SavingsRoute: SavingsRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SwaggerRoute: SwaggerRoute,
  TermsRoute: TermsRoute,
  TransactionsRoute: TransactionsRoute,
  WishlistRoute: WishlistRoute,
  ApiCategoriesRoute: ApiCategoriesRouteWithChildren,
  ApiExchangeRateRoute: ApiExchangeRateRoute,
  ApiGoalsRoute: ApiGoalsRouteWithChildren,
  ApiPaymentAccountsRoute: ApiPaymentAccountsRouteWithChildren,
  ApiSavingsRoute: ApiSavingsRouteWithChildren,
  ApiTransactionsRoute: ApiTransactionsRouteWithChildren,
  ApiWishlistRoute: ApiWishlistRouteWithChildren,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiConversationsRoute: ApiAiConversationsRouteWithChildren,
  ApiAiTransactionRoute: ApiAiTransactionRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOpenapiJsonRoute: ApiOpenapiJsonRoute,
  ApiSettingsAiRoute: ApiSettingsAiRouteWithChildren,
  ApiSettingsCurrencyRoute: ApiSettingsCurrencyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
