/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SwaggerRouteImport } from './routes/swagger'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SetupSecurityRouteImport } from './routes/setup-security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AccountSuspendedRouteImport } from './routes/account-suspended'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWishlistRouteImport } from './routes/api/wishlist'
import { Route as ApiTransactionsRouteImport } from './routes/api/transactions'
import { Route as ApiSavingsRouteImport } from './routes/api/savings'
import { Route as ApiRecurringRouteImport } from './routes/api/recurring'
import { Route as ApiPaymentAccountsRouteImport } from './routes/api/payment-accounts'
import { Route as ApiGoalsRouteImport } from './routes/api/goals'
import { Route as ApiExchangeRateRouteImport } from './routes/api/exchange-rate'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiWishlistIdRouteImport } from './routes/api/wishlist/$id'
import { Route as ApiTransactionsIdRouteImport } from './routes/api/transactions/$id'
import { Route as ApiSettingsCurrencyRouteImport } from './routes/api/settings/currency'
import { Route as ApiSettingsAiRouteImport } from './routes/api/settings/ai'
import { Route as ApiSavingsIdRouteImport } from './routes/api/savings/$id'
import { Route as ApiRecurringIdRouteImport } from './routes/api/recurring/$id'
import { Route as ApiPaymentAccountsIdRouteImport } from './routes/api/payment-accounts/$id'
import { Route as ApiOpenapiJsonRouteImport } from './routes/api/openapi.json'
import { Route as ApiGoalsIdRouteImport } from './routes/api/goals/$id'
import { Route as ApiCronRunRecurringRouteImport } from './routes/api/cron/run-recurring'
import { Route as ApiCategoriesIdRouteImport } from './routes/api/categories/$id'
import { Route as ApiAuthSignInModerationRouteImport } from './routes/api/auth/sign-in-moderation'
import { Route as ApiAuthSecurityProfileRouteImport } from './routes/api/auth/security-profile'
import { Route as ApiAuthModerationStatusRouteImport } from './routes/api/auth/moderation-status'
import { Route as ApiAuthChangePasswordRouteImport } from './routes/api/auth/change-password'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiTransactionRouteImport } from './routes/api/ai/transaction'
import { Route as ApiAiConversationsRouteImport } from './routes/api/ai/conversations'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminGlobalAiRouteImport } from './routes/api/admin/global-ai'
import { Route as ApiAdminCategoriesRouteImport } from './routes/api/admin/categories'
import { Route as ApiSettingsAiTestRouteImport } from './routes/api/settings/ai/test'
import { Route as ApiSettingsAiKeyRouteImport } from './routes/api/settings/ai/key'
import { Route as ApiAuthRecoveryResetRouteImport } from './routes/api/auth/recovery/reset'
import { Route as ApiAuthRecoveryChallengeRouteImport } from './routes/api/auth/recovery/challenge'
import { Route as ApiAiConversationsConversationIdRouteImport } from './routes/api/ai/conversations/$conversationId'
import { Route as ApiAdminUsersIdRouteImport } from './routes/api/admin/users/$id'
import { Route as ApiAdminGlobalAiTestRouteImport } from './routes/api/admin/global-ai/test'
import { Route as ApiAdminGlobalAiKeyRouteImport } from './routes/api/admin/global-ai/key'
import { Route as ApiAdminCategoriesIdRouteImport } from './routes/api/admin/categories/$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SwaggerRoute = SwaggerRouteImport.update({
  id: '/swagger',
  path: '/swagger',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupSecurityRoute = SetupSecurityRouteImport.update({
  id: '/setup-security',
  path: '/setup-security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSuspendedRoute = AccountSuspendedRouteImport.update({
  id: '/account-suspended',
  path: '/account-suspended',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWishlistRoute = ApiWishlistRouteImport.update({
  id: '/api/wishlist',
  path: '/api/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsRoute = ApiTransactionsRouteImport.update({
  id: '/api/transactions',
  path: '/api/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSavingsRoute = ApiSavingsRouteImport.update({
  id: '/api/savings',
  path: '/api/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecurringRoute = ApiRecurringRouteImport.update({
  id: '/api/recurring',
  path: '/api/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentAccountsRoute = ApiPaymentAccountsRouteImport.update({
  id: '/api/payment-accounts',
  path: '/api/payment-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoalsRoute = ApiGoalsRouteImport.update({
  id: '/api/goals',
  path: '/api/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExchangeRateRoute = ApiExchangeRateRouteImport.update({
  id: '/api/exchange-rate',
  path: '/api/exchange-rate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWishlistIdRoute = ApiWishlistIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiWishlistRoute,
} as any)
const ApiTransactionsIdRoute = ApiTransactionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTransactionsRoute,
} as any)
const ApiSettingsCurrencyRoute = ApiSettingsCurrencyRouteImport.update({
  id: '/api/settings/currency',
  path: '/api/settings/currency',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsAiRoute = ApiSettingsAiRouteImport.update({
  id: '/api/settings/ai',
  path: '/api/settings/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSavingsIdRoute = ApiSavingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSavingsRoute,
} as any)
const ApiRecurringIdRoute = ApiRecurringIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiRecurringRoute,
} as any)
const ApiPaymentAccountsIdRoute = ApiPaymentAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPaymentAccountsRoute,
} as any)
const ApiOpenapiJsonRoute = ApiOpenapiJsonRouteImport.update({
  id: '/api/openapi/json',
  path: '/api/openapi/json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoalsIdRoute = ApiGoalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiGoalsRoute,
} as any)
const ApiCronRunRecurringRoute = ApiCronRunRecurringRouteImport.update({
  id: '/api/cron/run-recurring',
  path: '/api/cron/run-recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesIdRoute = ApiCategoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCategoriesRoute,
} as any)
const ApiAuthSignInModerationRoute = ApiAuthSignInModerationRouteImport.update({
  id: '/api/auth/sign-in-moderation',
  path: '/api/auth/sign-in-moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSecurityProfileRoute = ApiAuthSecurityProfileRouteImport.update({
  id: '/api/auth/security-profile',
  path: '/api/auth/security-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthModerationStatusRoute = ApiAuthModerationStatusRouteImport.update({
  id: '/api/auth/moderation-status',
  path: '/api/auth/moderation-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthChangePasswordRoute = ApiAuthChangePasswordRouteImport.update({
  id: '/api/auth/change-password',
  path: '/api/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTransactionRoute = ApiAiTransactionRouteImport.update({
  id: '/api/ai/transaction',
  path: '/api/ai/transaction',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiConversationsRoute = ApiAiConversationsRouteImport.update({
  id: '/api/ai/conversations',
  path: '/api/ai/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGlobalAiRoute = ApiAdminGlobalAiRouteImport.update({
  id: '/api/admin/global-ai',
  path: '/api/admin/global-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCategoriesRoute = ApiAdminCategoriesRouteImport.update({
  id: '/api/admin/categories',
  path: '/api/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsAiTestRoute = ApiSettingsAiTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiSettingsAiRoute,
} as any)
const ApiSettingsAiKeyRoute = ApiSettingsAiKeyRouteImport.update({
  id: '/key',
  path: '/key',
  getParentRoute: () => ApiSettingsAiRoute,
} as any)
const ApiAuthRecoveryResetRoute = ApiAuthRecoveryResetRouteImport.update({
  id: '/api/auth/recovery/reset',
  path: '/api/auth/recovery/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRecoveryChallengeRoute =
  ApiAuthRecoveryChallengeRouteImport.update({
    id: '/api/auth/recovery/challenge',
    path: '/api/auth/recovery/challenge',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiConversationsConversationIdRoute =
  ApiAiConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => ApiAiConversationsRoute,
  } as any)
const ApiAdminUsersIdRoute = ApiAdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminUsersRoute,
} as any)
const ApiAdminGlobalAiTestRoute = ApiAdminGlobalAiTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiAdminGlobalAiRoute,
} as any)
const ApiAdminGlobalAiKeyRoute = ApiAdminGlobalAiKeyRouteImport.update({
  id: '/key',
  path: '/key',
  getParentRoute: () => ApiAdminGlobalAiRoute,
} as any)
const ApiAdminCategoriesIdRoute = ApiAdminCategoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminCategoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-suspended': typeof AccountSuspendedRoute
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/categories': typeof CategoriesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/privacy': typeof PrivacyRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/setup-security': typeof SetupSecurityRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/swagger': typeof SwaggerRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/wishlist': typeof WishlistRoute
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/exchange-rate': typeof ApiExchangeRateRoute
  '/api/goals': typeof ApiGoalsRouteWithChildren
  '/api/payment-accounts': typeof ApiPaymentAccountsRouteWithChildren
  '/api/recurring': typeof ApiRecurringRouteWithChildren
  '/api/savings': typeof ApiSavingsRouteWithChildren
  '/api/transactions': typeof ApiTransactionsRouteWithChildren
  '/api/wishlist': typeof ApiWishlistRouteWithChildren
  '/api/admin/categories': typeof ApiAdminCategoriesRouteWithChildren
  '/api/admin/global-ai': typeof ApiAdminGlobalAiRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/conversations': typeof ApiAiConversationsRouteWithChildren
  '/api/ai/transaction': typeof ApiAiTransactionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/moderation-status': typeof ApiAuthModerationStatusRoute
  '/api/auth/security-profile': typeof ApiAuthSecurityProfileRoute
  '/api/auth/sign-in-moderation': typeof ApiAuthSignInModerationRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/cron/run-recurring': typeof ApiCronRunRecurringRoute
  '/api/goals/$id': typeof ApiGoalsIdRoute
  '/api/openapi/json': typeof ApiOpenapiJsonRoute
  '/api/payment-accounts/$id': typeof ApiPaymentAccountsIdRoute
  '/api/recurring/$id': typeof ApiRecurringIdRoute
  '/api/savings/$id': typeof ApiSavingsIdRoute
  '/api/settings/ai': typeof ApiSettingsAiRouteWithChildren
  '/api/settings/currency': typeof ApiSettingsCurrencyRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/api/wishlist/$id': typeof ApiWishlistIdRoute
  '/api/admin/categories/$id': typeof ApiAdminCategoriesIdRoute
  '/api/admin/global-ai/key': typeof ApiAdminGlobalAiKeyRoute
  '/api/admin/global-ai/test': typeof ApiAdminGlobalAiTestRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/ai/conversations/$conversationId': typeof ApiAiConversationsConversationIdRoute
  '/api/auth/recovery/challenge': typeof ApiAuthRecoveryChallengeRoute
  '/api/auth/recovery/reset': typeof ApiAuthRecoveryResetRoute
  '/api/settings/ai/key': typeof ApiSettingsAiKeyRoute
  '/api/settings/ai/test': typeof ApiSettingsAiTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-suspended': typeof AccountSuspendedRoute
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/categories': typeof CategoriesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/privacy': typeof PrivacyRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/setup-security': typeof SetupSecurityRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/swagger': typeof SwaggerRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/wishlist': typeof WishlistRoute
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/exchange-rate': typeof ApiExchangeRateRoute
  '/api/goals': typeof ApiGoalsRouteWithChildren
  '/api/payment-accounts': typeof ApiPaymentAccountsRouteWithChildren
  '/api/recurring': typeof ApiRecurringRouteWithChildren
  '/api/savings': typeof ApiSavingsRouteWithChildren
  '/api/transactions': typeof ApiTransactionsRouteWithChildren
  '/api/wishlist': typeof ApiWishlistRouteWithChildren
  '/api/admin/categories': typeof ApiAdminCategoriesRouteWithChildren
  '/api/admin/global-ai': typeof ApiAdminGlobalAiRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/conversations': typeof ApiAiConversationsRouteWithChildren
  '/api/ai/transaction': typeof ApiAiTransactionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/moderation-status': typeof ApiAuthModerationStatusRoute
  '/api/auth/security-profile': typeof ApiAuthSecurityProfileRoute
  '/api/auth/sign-in-moderation': typeof ApiAuthSignInModerationRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/cron/run-recurring': typeof ApiCronRunRecurringRoute
  '/api/goals/$id': typeof ApiGoalsIdRoute
  '/api/openapi/json': typeof ApiOpenapiJsonRoute
  '/api/payment-accounts/$id': typeof ApiPaymentAccountsIdRoute
  '/api/recurring/$id': typeof ApiRecurringIdRoute
  '/api/savings/$id': typeof ApiSavingsIdRoute
  '/api/settings/ai': typeof ApiSettingsAiRouteWithChildren
  '/api/settings/currency': typeof ApiSettingsCurrencyRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/api/wishlist/$id': typeof ApiWishlistIdRoute
  '/api/admin/categories/$id': typeof ApiAdminCategoriesIdRoute
  '/api/admin/global-ai/key': typeof ApiAdminGlobalAiKeyRoute
  '/api/admin/global-ai/test': typeof ApiAdminGlobalAiTestRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/ai/conversations/$conversationId': typeof ApiAiConversationsConversationIdRoute
  '/api/auth/recovery/challenge': typeof ApiAuthRecoveryChallengeRoute
  '/api/auth/recovery/reset': typeof ApiAuthRecoveryResetRoute
  '/api/settings/ai/key': typeof ApiSettingsAiKeyRoute
  '/api/settings/ai/test': typeof ApiSettingsAiTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-suspended': typeof AccountSuspendedRoute
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/categories': typeof CategoriesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goals': typeof GoalsRoute
  '/privacy': typeof PrivacyRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/setup-security': typeof SetupSecurityRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/swagger': typeof SwaggerRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/wishlist': typeof WishlistRoute
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/exchange-rate': typeof ApiExchangeRateRoute
  '/api/goals': typeof ApiGoalsRouteWithChildren
  '/api/payment-accounts': typeof ApiPaymentAccountsRouteWithChildren
  '/api/recurring': typeof ApiRecurringRouteWithChildren
  '/api/savings': typeof ApiSavingsRouteWithChildren
  '/api/transactions': typeof ApiTransactionsRouteWithChildren
  '/api/wishlist': typeof ApiWishlistRouteWithChildren
  '/api/admin/categories': typeof ApiAdminCategoriesRouteWithChildren
  '/api/admin/global-ai': typeof ApiAdminGlobalAiRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/conversations': typeof ApiAiConversationsRouteWithChildren
  '/api/ai/transaction': typeof ApiAiTransactionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/moderation-status': typeof ApiAuthModerationStatusRoute
  '/api/auth/security-profile': typeof ApiAuthSecurityProfileRoute
  '/api/auth/sign-in-moderation': typeof ApiAuthSignInModerationRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/cron/run-recurring': typeof ApiCronRunRecurringRoute
  '/api/goals/$id': typeof ApiGoalsIdRoute
  '/api/openapi/json': typeof ApiOpenapiJsonRoute
  '/api/payment-accounts/$id': typeof ApiPaymentAccountsIdRoute
  '/api/recurring/$id': typeof ApiRecurringIdRoute
  '/api/savings/$id': typeof ApiSavingsIdRoute
  '/api/settings/ai': typeof ApiSettingsAiRouteWithChildren
  '/api/settings/currency': typeof ApiSettingsCurrencyRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/api/wishlist/$id': typeof ApiWishlistIdRoute
  '/api/admin/categories/$id': typeof ApiAdminCategoriesIdRoute
  '/api/admin/global-ai/key': typeof ApiAdminGlobalAiKeyRoute
  '/api/admin/global-ai/test': typeof ApiAdminGlobalAiTestRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
  '/api/ai/conversations/$conversationId': typeof ApiAiConversationsConversationIdRoute
  '/api/auth/recovery/challenge': typeof ApiAuthRecoveryChallengeRoute
  '/api/auth/recovery/reset': typeof ApiAuthRecoveryResetRoute
  '/api/settings/ai/key': typeof ApiSettingsAiKeyRoute
  '/api/settings/ai/test': typeof ApiSettingsAiTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-suspended'
    | '/accounts'
    | '/admin'
    | '/analytics'
    | '/categories'
    | '/forgot-password'
    | '/goals'
    | '/privacy'
    | '/savings'
    | '/settings'
    | '/setup-security'
    | '/sign-in'
    | '/sign-up'
    | '/swagger'
    | '/terms'
    | '/transactions'
    | '/wishlist'
    | '/api/categories'
    | '/api/exchange-rate'
    | '/api/goals'
    | '/api/payment-accounts'
    | '/api/recurring'
    | '/api/savings'
    | '/api/transactions'
    | '/api/wishlist'
    | '/api/admin/categories'
    | '/api/admin/global-ai'
    | '/api/admin/users'
    | '/api/ai/chat'
    | '/api/ai/conversations'
    | '/api/ai/transaction'
    | '/api/auth/$'
    | '/api/auth/change-password'
    | '/api/auth/moderation-status'
    | '/api/auth/security-profile'
    | '/api/auth/sign-in-moderation'
    | '/api/categories/$id'
    | '/api/cron/run-recurring'
    | '/api/goals/$id'
    | '/api/openapi/json'
    | '/api/payment-accounts/$id'
    | '/api/recurring/$id'
    | '/api/savings/$id'
    | '/api/settings/ai'
    | '/api/settings/currency'
    | '/api/transactions/$id'
    | '/api/wishlist/$id'
    | '/api/admin/categories/$id'
    | '/api/admin/global-ai/key'
    | '/api/admin/global-ai/test'
    | '/api/admin/users/$id'
    | '/api/ai/conversations/$conversationId'
    | '/api/auth/recovery/challenge'
    | '/api/auth/recovery/reset'
    | '/api/settings/ai/key'
    | '/api/settings/ai/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-suspended'
    | '/accounts'
    | '/admin'
    | '/analytics'
    | '/categories'
    | '/forgot-password'
    | '/goals'
    | '/privacy'
    | '/savings'
    | '/settings'
    | '/setup-security'
    | '/sign-in'
    | '/sign-up'
    | '/swagger'
    | '/terms'
    | '/transactions'
    | '/wishlist'
    | '/api/categories'
    | '/api/exchange-rate'
    | '/api/goals'
    | '/api/payment-accounts'
    | '/api/recurring'
    | '/api/savings'
    | '/api/transactions'
    | '/api/wishlist'
    | '/api/admin/categories'
    | '/api/admin/global-ai'
    | '/api/admin/users'
    | '/api/ai/chat'
    | '/api/ai/conversations'
    | '/api/ai/transaction'
    | '/api/auth/$'
    | '/api/auth/change-password'
    | '/api/auth/moderation-status'
    | '/api/auth/security-profile'
    | '/api/auth/sign-in-moderation'
    | '/api/categories/$id'
    | '/api/cron/run-recurring'
    | '/api/goals/$id'
    | '/api/openapi/json'
    | '/api/payment-accounts/$id'
    | '/api/recurring/$id'
    | '/api/savings/$id'
    | '/api/settings/ai'
    | '/api/settings/currency'
    | '/api/transactions/$id'
    | '/api/wishlist/$id'
    | '/api/admin/categories/$id'
    | '/api/admin/global-ai/key'
    | '/api/admin/global-ai/test'
    | '/api/admin/users/$id'
    | '/api/ai/conversations/$conversationId'
    | '/api/auth/recovery/challenge'
    | '/api/auth/recovery/reset'
    | '/api/settings/ai/key'
    | '/api/settings/ai/test'
  id:
    | '__root__'
    | '/'
    | '/account-suspended'
    | '/accounts'
    | '/admin'
    | '/analytics'
    | '/categories'
    | '/forgot-password'
    | '/goals'
    | '/privacy'
    | '/savings'
    | '/settings'
    | '/setup-security'
    | '/sign-in'
    | '/sign-up'
    | '/swagger'
    | '/terms'
    | '/transactions'
    | '/wishlist'
    | '/api/categories'
    | '/api/exchange-rate'
    | '/api/goals'
    | '/api/payment-accounts'
    | '/api/recurring'
    | '/api/savings'
    | '/api/transactions'
    | '/api/wishlist'
    | '/api/admin/categories'
    | '/api/admin/global-ai'
    | '/api/admin/users'
    | '/api/ai/chat'
    | '/api/ai/conversations'
    | '/api/ai/transaction'
    | '/api/auth/$'
    | '/api/auth/change-password'
    | '/api/auth/moderation-status'
    | '/api/auth/security-profile'
    | '/api/auth/sign-in-moderation'
    | '/api/categories/$id'
    | '/api/cron/run-recurring'
    | '/api/goals/$id'
    | '/api/openapi/json'
    | '/api/payment-accounts/$id'
    | '/api/recurring/$id'
    | '/api/savings/$id'
    | '/api/settings/ai'
    | '/api/settings/currency'
    | '/api/transactions/$id'
    | '/api/wishlist/$id'
    | '/api/admin/categories/$id'
    | '/api/admin/global-ai/key'
    | '/api/admin/global-ai/test'
    | '/api/admin/users/$id'
    | '/api/ai/conversations/$conversationId'
    | '/api/auth/recovery/challenge'
    | '/api/auth/recovery/reset'
    | '/api/settings/ai/key'
    | '/api/settings/ai/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountSuspendedRoute: typeof AccountSuspendedRoute
  AccountsRoute: typeof AccountsRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CategoriesRoute: typeof CategoriesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GoalsRoute: typeof GoalsRoute
  PrivacyRoute: typeof PrivacyRoute
  SavingsRoute: typeof SavingsRoute
  SettingsRoute: typeof SettingsRoute
  SetupSecurityRoute: typeof SetupSecurityRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SwaggerRoute: typeof SwaggerRoute
  TermsRoute: typeof TermsRoute
  TransactionsRoute: typeof TransactionsRoute
  WishlistRoute: typeof WishlistRoute
  ApiCategoriesRoute: typeof ApiCategoriesRouteWithChildren
  ApiExchangeRateRoute: typeof ApiExchangeRateRoute
  ApiGoalsRoute: typeof ApiGoalsRouteWithChildren
  ApiPaymentAccountsRoute: typeof ApiPaymentAccountsRouteWithChildren
  ApiRecurringRoute: typeof ApiRecurringRouteWithChildren
  ApiSavingsRoute: typeof ApiSavingsRouteWithChildren
  ApiTransactionsRoute: typeof ApiTransactionsRouteWithChildren
  ApiWishlistRoute: typeof ApiWishlistRouteWithChildren
  ApiAdminCategoriesRoute: typeof ApiAdminCategoriesRouteWithChildren
  ApiAdminGlobalAiRoute: typeof ApiAdminGlobalAiRouteWithChildren
  ApiAdminUsersRoute: typeof ApiAdminUsersRouteWithChildren
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiConversationsRoute: typeof ApiAiConversationsRouteWithChildren
  ApiAiTransactionRoute: typeof ApiAiTransactionRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthChangePasswordRoute: typeof ApiAuthChangePasswordRoute
  ApiAuthModerationStatusRoute: typeof ApiAuthModerationStatusRoute
  ApiAuthSecurityProfileRoute: typeof ApiAuthSecurityProfileRoute
  ApiAuthSignInModerationRoute: typeof ApiAuthSignInModerationRoute
  ApiCronRunRecurringRoute: typeof ApiCronRunRecurringRoute
  ApiOpenapiJsonRoute: typeof ApiOpenapiJsonRoute
  ApiSettingsAiRoute: typeof ApiSettingsAiRouteWithChildren
  ApiSettingsCurrencyRoute: typeof ApiSettingsCurrencyRoute
  ApiAuthRecoveryChallengeRoute: typeof ApiAuthRecoveryChallengeRoute
  ApiAuthRecoveryResetRoute: typeof ApiAuthRecoveryResetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swagger': {
      id: '/swagger'
      path: '/swagger'
      fullPath: '/swagger'
      preLoaderRoute: typeof SwaggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-security': {
      id: '/setup-security'
      path: '/setup-security'
      fullPath: '/setup-security'
      preLoaderRoute: typeof SetupSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-suspended': {
      id: '/account-suspended'
      path: '/account-suspended'
      fullPath: '/account-suspended'
      preLoaderRoute: typeof AccountSuspendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wishlist': {
      id: '/api/wishlist'
      path: '/api/wishlist'
      fullPath: '/api/wishlist'
      preLoaderRoute: typeof ApiWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions': {
      id: '/api/transactions'
      path: '/api/transactions'
      fullPath: '/api/transactions'
      preLoaderRoute: typeof ApiTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/savings': {
      id: '/api/savings'
      path: '/api/savings'
      fullPath: '/api/savings'
      preLoaderRoute: typeof ApiSavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recurring': {
      id: '/api/recurring'
      path: '/api/recurring'
      fullPath: '/api/recurring'
      preLoaderRoute: typeof ApiRecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment-accounts': {
      id: '/api/payment-accounts'
      path: '/api/payment-accounts'
      fullPath: '/api/payment-accounts'
      preLoaderRoute: typeof ApiPaymentAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/goals': {
      id: '/api/goals'
      path: '/api/goals'
      fullPath: '/api/goals'
      preLoaderRoute: typeof ApiGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exchange-rate': {
      id: '/api/exchange-rate'
      path: '/api/exchange-rate'
      fullPath: '/api/exchange-rate'
      preLoaderRoute: typeof ApiExchangeRateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wishlist/$id': {
      id: '/api/wishlist/$id'
      path: '/$id'
      fullPath: '/api/wishlist/$id'
      preLoaderRoute: typeof ApiWishlistIdRouteImport
      parentRoute: typeof ApiWishlistRoute
    }
    '/api/transactions/$id': {
      id: '/api/transactions/$id'
      path: '/$id'
      fullPath: '/api/transactions/$id'
      preLoaderRoute: typeof ApiTransactionsIdRouteImport
      parentRoute: typeof ApiTransactionsRoute
    }
    '/api/settings/currency': {
      id: '/api/settings/currency'
      path: '/api/settings/currency'
      fullPath: '/api/settings/currency'
      preLoaderRoute: typeof ApiSettingsCurrencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/ai': {
      id: '/api/settings/ai'
      path: '/api/settings/ai'
      fullPath: '/api/settings/ai'
      preLoaderRoute: typeof ApiSettingsAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/savings/$id': {
      id: '/api/savings/$id'
      path: '/$id'
      fullPath: '/api/savings/$id'
      preLoaderRoute: typeof ApiSavingsIdRouteImport
      parentRoute: typeof ApiSavingsRoute
    }
    '/api/recurring/$id': {
      id: '/api/recurring/$id'
      path: '/$id'
      fullPath: '/api/recurring/$id'
      preLoaderRoute: typeof ApiRecurringIdRouteImport
      parentRoute: typeof ApiRecurringRoute
    }
    '/api/payment-accounts/$id': {
      id: '/api/payment-accounts/$id'
      path: '/$id'
      fullPath: '/api/payment-accounts/$id'
      preLoaderRoute: typeof ApiPaymentAccountsIdRouteImport
      parentRoute: typeof ApiPaymentAccountsRoute
    }
    '/api/openapi/json': {
      id: '/api/openapi/json'
      path: '/api/openapi/json'
      fullPath: '/api/openapi/json'
      preLoaderRoute: typeof ApiOpenapiJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/goals/$id': {
      id: '/api/goals/$id'
      path: '/$id'
      fullPath: '/api/goals/$id'
      preLoaderRoute: typeof ApiGoalsIdRouteImport
      parentRoute: typeof ApiGoalsRoute
    }
    '/api/cron/run-recurring': {
      id: '/api/cron/run-recurring'
      path: '/api/cron/run-recurring'
      fullPath: '/api/cron/run-recurring'
      preLoaderRoute: typeof ApiCronRunRecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories/$id': {
      id: '/api/categories/$id'
      path: '/$id'
      fullPath: '/api/categories/$id'
      preLoaderRoute: typeof ApiCategoriesIdRouteImport
      parentRoute: typeof ApiCategoriesRoute
    }
    '/api/auth/sign-in-moderation': {
      id: '/api/auth/sign-in-moderation'
      path: '/api/auth/sign-in-moderation'
      fullPath: '/api/auth/sign-in-moderation'
      preLoaderRoute: typeof ApiAuthSignInModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/security-profile': {
      id: '/api/auth/security-profile'
      path: '/api/auth/security-profile'
      fullPath: '/api/auth/security-profile'
      preLoaderRoute: typeof ApiAuthSecurityProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/moderation-status': {
      id: '/api/auth/moderation-status'
      path: '/api/auth/moderation-status'
      fullPath: '/api/auth/moderation-status'
      preLoaderRoute: typeof ApiAuthModerationStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/change-password': {
      id: '/api/auth/change-password'
      path: '/api/auth/change-password'
      fullPath: '/api/auth/change-password'
      preLoaderRoute: typeof ApiAuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/transaction': {
      id: '/api/ai/transaction'
      path: '/api/ai/transaction'
      fullPath: '/api/ai/transaction'
      preLoaderRoute: typeof ApiAiTransactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/conversations': {
      id: '/api/ai/conversations'
      path: '/api/ai/conversations'
      fullPath: '/api/ai/conversations'
      preLoaderRoute: typeof ApiAiConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/global-ai': {
      id: '/api/admin/global-ai'
      path: '/api/admin/global-ai'
      fullPath: '/api/admin/global-ai'
      preLoaderRoute: typeof ApiAdminGlobalAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/categories': {
      id: '/api/admin/categories'
      path: '/api/admin/categories'
      fullPath: '/api/admin/categories'
      preLoaderRoute: typeof ApiAdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/ai/test': {
      id: '/api/settings/ai/test'
      path: '/test'
      fullPath: '/api/settings/ai/test'
      preLoaderRoute: typeof ApiSettingsAiTestRouteImport
      parentRoute: typeof ApiSettingsAiRoute
    }
    '/api/settings/ai/key': {
      id: '/api/settings/ai/key'
      path: '/key'
      fullPath: '/api/settings/ai/key'
      preLoaderRoute: typeof ApiSettingsAiKeyRouteImport
      parentRoute: typeof ApiSettingsAiRoute
    }
    '/api/auth/recovery/reset': {
      id: '/api/auth/recovery/reset'
      path: '/api/auth/recovery/reset'
      fullPath: '/api/auth/recovery/reset'
      preLoaderRoute: typeof ApiAuthRecoveryResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/recovery/challenge': {
      id: '/api/auth/recovery/challenge'
      path: '/api/auth/recovery/challenge'
      fullPath: '/api/auth/recovery/challenge'
      preLoaderRoute: typeof ApiAuthRecoveryChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/conversations/$conversationId': {
      id: '/api/ai/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/api/ai/conversations/$conversationId'
      preLoaderRoute: typeof ApiAiConversationsConversationIdRouteImport
      parentRoute: typeof ApiAiConversationsRoute
    }
    '/api/admin/users/$id': {
      id: '/api/admin/users/$id'
      path: '/$id'
      fullPath: '/api/admin/users/$id'
      preLoaderRoute: typeof ApiAdminUsersIdRouteImport
      parentRoute: typeof ApiAdminUsersRoute
    }
    '/api/admin/global-ai/test': {
      id: '/api/admin/global-ai/test'
      path: '/test'
      fullPath: '/api/admin/global-ai/test'
      preLoaderRoute: typeof ApiAdminGlobalAiTestRouteImport
      parentRoute: typeof ApiAdminGlobalAiRoute
    }
    '/api/admin/global-ai/key': {
      id: '/api/admin/global-ai/key'
      path: '/key'
      fullPath: '/api/admin/global-ai/key'
      preLoaderRoute: typeof ApiAdminGlobalAiKeyRouteImport
      parentRoute: typeof ApiAdminGlobalAiRoute
    }
    '/api/admin/categories/$id': {
      id: '/api/admin/categories/$id'
      path: '/$id'
      fullPath: '/api/admin/categories/$id'
      preLoaderRoute: typeof ApiAdminCategoriesIdRouteImport
      parentRoute: typeof ApiAdminCategoriesRoute
    }
  }
}

interface ApiCategoriesRouteChildren {
  ApiCategoriesIdRoute: typeof ApiCategoriesIdRoute
}

const ApiCategoriesRouteChildren: ApiCategoriesRouteChildren = {
  ApiCategoriesIdRoute: ApiCategoriesIdRoute,
}

const ApiCategoriesRouteWithChildren = ApiCategoriesRoute._addFileChildren(
  ApiCategoriesRouteChildren,
)

interface ApiGoalsRouteChildren {
  ApiGoalsIdRoute: typeof ApiGoalsIdRoute
}

const ApiGoalsRouteChildren: ApiGoalsRouteChildren = {
  ApiGoalsIdRoute: ApiGoalsIdRoute,
}

const ApiGoalsRouteWithChildren = ApiGoalsRoute._addFileChildren(
  ApiGoalsRouteChildren,
)

interface ApiPaymentAccountsRouteChildren {
  ApiPaymentAccountsIdRoute: typeof ApiPaymentAccountsIdRoute
}

const ApiPaymentAccountsRouteChildren: ApiPaymentAccountsRouteChildren = {
  ApiPaymentAccountsIdRoute: ApiPaymentAccountsIdRoute,
}

const ApiPaymentAccountsRouteWithChildren =
  ApiPaymentAccountsRoute._addFileChildren(ApiPaymentAccountsRouteChildren)

interface ApiRecurringRouteChildren {
  ApiRecurringIdRoute: typeof ApiRecurringIdRoute
}

const ApiRecurringRouteChildren: ApiRecurringRouteChildren = {
  ApiRecurringIdRoute: ApiRecurringIdRoute,
}

const ApiRecurringRouteWithChildren = ApiRecurringRoute._addFileChildren(
  ApiRecurringRouteChildren,
)

interface ApiSavingsRouteChildren {
  ApiSavingsIdRoute: typeof ApiSavingsIdRoute
}

const ApiSavingsRouteChildren: ApiSavingsRouteChildren = {
  ApiSavingsIdRoute: ApiSavingsIdRoute,
}

const ApiSavingsRouteWithChildren = ApiSavingsRoute._addFileChildren(
  ApiSavingsRouteChildren,
)

interface ApiTransactionsRouteChildren {
  ApiTransactionsIdRoute: typeof ApiTransactionsIdRoute
}

const ApiTransactionsRouteChildren: ApiTransactionsRouteChildren = {
  ApiTransactionsIdRoute: ApiTransactionsIdRoute,
}

const ApiTransactionsRouteWithChildren = ApiTransactionsRoute._addFileChildren(
  ApiTransactionsRouteChildren,
)

interface ApiWishlistRouteChildren {
  ApiWishlistIdRoute: typeof ApiWishlistIdRoute
}

const ApiWishlistRouteChildren: ApiWishlistRouteChildren = {
  ApiWishlistIdRoute: ApiWishlistIdRoute,
}

const ApiWishlistRouteWithChildren = ApiWishlistRoute._addFileChildren(
  ApiWishlistRouteChildren,
)

interface ApiAdminCategoriesRouteChildren {
  ApiAdminCategoriesIdRoute: typeof ApiAdminCategoriesIdRoute
}

const ApiAdminCategoriesRouteChildren: ApiAdminCategoriesRouteChildren = {
  ApiAdminCategoriesIdRoute: ApiAdminCategoriesIdRoute,
}

const ApiAdminCategoriesRouteWithChildren =
  ApiAdminCategoriesRoute._addFileChildren(ApiAdminCategoriesRouteChildren)

interface ApiAdminGlobalAiRouteChildren {
  ApiAdminGlobalAiKeyRoute: typeof ApiAdminGlobalAiKeyRoute
  ApiAdminGlobalAiTestRoute: typeof ApiAdminGlobalAiTestRoute
}

const ApiAdminGlobalAiRouteChildren: ApiAdminGlobalAiRouteChildren = {
  ApiAdminGlobalAiKeyRoute: ApiAdminGlobalAiKeyRoute,
  ApiAdminGlobalAiTestRoute: ApiAdminGlobalAiTestRoute,
}

const ApiAdminGlobalAiRouteWithChildren =
  ApiAdminGlobalAiRoute._addFileChildren(ApiAdminGlobalAiRouteChildren)

interface ApiAdminUsersRouteChildren {
  ApiAdminUsersIdRoute: typeof ApiAdminUsersIdRoute
}

const ApiAdminUsersRouteChildren: ApiAdminUsersRouteChildren = {
  ApiAdminUsersIdRoute: ApiAdminUsersIdRoute,
}

const ApiAdminUsersRouteWithChildren = ApiAdminUsersRoute._addFileChildren(
  ApiAdminUsersRouteChildren,
)

interface ApiAiConversationsRouteChildren {
  ApiAiConversationsConversationIdRoute: typeof ApiAiConversationsConversationIdRoute
}

const ApiAiConversationsRouteChildren: ApiAiConversationsRouteChildren = {
  ApiAiConversationsConversationIdRoute: ApiAiConversationsConversationIdRoute,
}

const ApiAiConversationsRouteWithChildren =
  ApiAiConversationsRoute._addFileChildren(ApiAiConversationsRouteChildren)

interface ApiSettingsAiRouteChildren {
  ApiSettingsAiKeyRoute: typeof ApiSettingsAiKeyRoute
  ApiSettingsAiTestRoute: typeof ApiSettingsAiTestRoute
}

const ApiSettingsAiRouteChildren: ApiSettingsAiRouteChildren = {
  ApiSettingsAiKeyRoute: ApiSettingsAiKeyRoute,
  ApiSettingsAiTestRoute: ApiSettingsAiTestRoute,
}

const ApiSettingsAiRouteWithChildren = ApiSettingsAiRoute._addFileChildren(
  ApiSettingsAiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountSuspendedRoute: AccountSuspendedRoute,
  AccountsRoute: AccountsRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  CategoriesRoute: CategoriesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GoalsRoute: GoalsRoute,
  PrivacyRoute: PrivacyRoute,
  SavingsRoute: SavingsRoute,
  SettingsRoute: SettingsRoute,
  SetupSecurityRoute: SetupSecurityRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SwaggerRoute: SwaggerRoute,
  TermsRoute: TermsRoute,
  TransactionsRoute: TransactionsRoute,
  WishlistRoute: WishlistRoute,
  ApiCategoriesRoute: ApiCategoriesRouteWithChildren,
  ApiExchangeRateRoute: ApiExchangeRateRoute,
  ApiGoalsRoute: ApiGoalsRouteWithChildren,
  ApiPaymentAccountsRoute: ApiPaymentAccountsRouteWithChildren,
  ApiRecurringRoute: ApiRecurringRouteWithChildren,
  ApiSavingsRoute: ApiSavingsRouteWithChildren,
  ApiTransactionsRoute: ApiTransactionsRouteWithChildren,
  ApiWishlistRoute: ApiWishlistRouteWithChildren,
  ApiAdminCategoriesRoute: ApiAdminCategoriesRouteWithChildren,
  ApiAdminGlobalAiRoute: ApiAdminGlobalAiRouteWithChildren,
  ApiAdminUsersRoute: ApiAdminUsersRouteWithChildren,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiConversationsRoute: ApiAiConversationsRouteWithChildren,
  ApiAiTransactionRoute: ApiAiTransactionRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthChangePasswordRoute: ApiAuthChangePasswordRoute,
  ApiAuthModerationStatusRoute: ApiAuthModerationStatusRoute,
  ApiAuthSecurityProfileRoute: ApiAuthSecurityProfileRoute,
  ApiAuthSignInModerationRoute: ApiAuthSignInModerationRoute,
  ApiCronRunRecurringRoute: ApiCronRunRecurringRoute,
  ApiOpenapiJsonRoute: ApiOpenapiJsonRoute,
  ApiSettingsAiRoute: ApiSettingsAiRouteWithChildren,
  ApiSettingsCurrencyRoute: ApiSettingsCurrencyRoute,
  ApiAuthRecoveryChallengeRoute: ApiAuthRecoveryChallengeRoute,
  ApiAuthRecoveryResetRoute: ApiAuthRecoveryResetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
